apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.secret.RABBITMQ_DEFAULT_USER }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secret.RABBITMQ_DEFAULT_PASS }}